import { ReactNode } from "react";
import { ShieldCheck, AlertCircle } from "lucide-react";
export const MINT = "#3E9C8A", CORAL = "#D9705F", LAV = "#B9AEDD", PEACH = "#F0B596", INK = "#223049", MUTED = "#5F6B7F";
export const LABELS: Record<string, string> = { Pregnancies: "Pregnancies", Glucose: "Glucose", BloodPressure: "Blood pressure",
  SkinThickness: "Skin thickness", Insulin: "Insulin", BMI: "BMI", DiabetesPedigreeFunction: "Diabetes pedigree function", Age: "Age" };
export const Disclaimer = () => (
  <p className="text-sm text-muted">Educational use only. This application does not provide a medical diagnosis. Please consult a qualified healthcare professional for medical advice.</p>
);
export const TrustCard = () => (
  <aside className="card" style={{ background: "var(--lavender)" }}>
    <h3 className="h-display flex items-center gap-2 text-xl"><ShieldCheck className="text-mintdeep" size={22} aria-hidden />Your health information matters 🛡️</h3>
    <p className="mt-2 text-ink/90">DiaInsight AI is an academic project designed for learning and research. Its predictions are generated by a machine-learning model and should not be considered a medical diagnosis.</p>
    <p className="mt-2 text-sm font-semibold text-mintdeep">No account required · No permanent patient database</p>
  </aside>
);
export const ErrorBox = ({ msg, onRetry }: { msg: string; onRetry?: () => void }) => (
  <div role="alert" className="card flex items-start gap-3" style={{ background: "var(--coral-soft)" }}>
    <AlertCircle className="mt-0.5 shrink-0 text-coral" aria-hidden />
    <div><p className="font-semibold">{msg}</p>{onRetry && <button onClick={onRetry} className="btn-ghost mt-3">Try again</button>}</div>
  </div>
);
export const Loading = ({ text }: { text: string }) => (
  <div className="flex flex-col items-center gap-3 py-16 text-muted" role="status"><span className="pulse-drop text-5xl" aria-hidden>💧</span><p>{text}</p></div>
);
export const Title = ({ children, sub }: { children: ReactNode; sub?: string }) => (
  <header className="mb-6"><h1 className="h-display text-3xl sm:text-4xl">{children}</h1>{sub && <p className="mt-2 max-w-2xl text-lg text-muted">{sub}</p>}</header>
);
